package ca.syncron.gui;

import org.slf4j.LoggerFactory;
import org.zu.ardulink.gui.DigitalPinStatus;

/**
 * Created by Dawson on 3/18/2015.
 */
public class DigitalOutputGui extends javax.swing.JFrame {
	static              String           nameId = DigitalOutputGui.class.getSimpleName();
	public final static org.slf4j.Logger log    = LoggerFactory.getLogger(nameId);
	private DigitalPinStatus mDigitalPinStatus1;


	// Variables declaration - do not modify
	private org.zu.ardulink.gui.DigitalPinStatus digitalPinStatus1;
	private javax.swing.JMenu                    jMenu1;
	private javax.swing.JMenu                    jMenu2;
	private javax.swing.JMenu                    jMenu3;
	private javax.swing.JMenuBar                 jMenuBar1;
	private javax.swing.JPopupMenu               jPopupMenu1;
	private DigitalPinStatus                     mDigitalPinStatus2;
	private org.zu.ardulink.gui.SwitchController switchController1;

	// End of variables declaration
	public DigitalOutputGui() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPopupMenu1 = new javax.swing.JPopupMenu();
		digitalPinStatus1 = new org.zu.ardulink.gui.DigitalPinStatus();
		switchController1 = new org.zu.ardulink.gui.SwitchController();
		switchController1.setPin(3);
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		jMenu3.setText("Settings");
		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);
		//mDigitalPinStatus2 = new DigitalPinStatus();
		//mDigitalPinStatus1.setPin(3);
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);

		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				      .addGroup(layout.createSequentialGroup()
				                      .addComponent(digitalPinStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				                      .addGap(18, 18, 18)
				                      .addComponent(switchController1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				                      .addGap(0, 173, Short.MAX_VALUE))
		                         );
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				      .addGroup(layout.createSequentialGroup()
				                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				                                      .addGroup(layout.createSequentialGroup()
				                                                      .addContainerGap()
				                                                      .addComponent(digitalPinStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				                                      .addGroup(layout.createSequentialGroup()
				                                                      .addGap(18, 18, 18)
				                                                      .addComponent(switchController1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				                      .addContainerGap(163, Short.MAX_VALUE))
		                       );

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info
					: javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DigitalOutputGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DigitalOutputGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DigitalOutputGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DigitalOutputGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

        /*
         * Create and display the form
         */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new DigitalOutputGui().setVisible(true);

			}
		});
	}

}
